[pom.xml]
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.Site_Gostar/DB/.app</groupId>
    <artifactId>Like_DB.sql</artifactId>
    <version>1</version>
    <relativePath>..Site_Gostar/DB/pom.xml</relativePath>
  </parent>
  <artifactId>modelo.css</artifactId>
</project>

[SNAPSHOTS]
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                      http://maven.apache.org/xsd/settings-1.0.0.xsd">

  <activeProfiles>
    <activeProfile>github</activeProfile>
  </activeProfiles>

  <profiles>
    <profile>
      <id>github</id>
      <repositories>
        <repository>
          <id>central</id>
          <url>https://repo.maven.apache.org/maven2</url>
        </repository>
        <repository>
          <id>github</id>
          <url>https://maven.pkg.github.com/Principalribeiroednilson1234/Site_Gostar/</url>
          <snapshots>
            <enabled>true</enabled>
          </snapshots>
        </repository>
      </repositories>
    </profile>
  </profiles>

  <servers>
    <server>
      <id>github</id>
      <username>ribeiroednilson1234/</username>
      <password>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</password>
    </server>
  </servers>
</settings>

[PUBLISH]
<distributionManagement>
   <repository>
     <id>github</id>
     <name>GitHub Site_Gostar/DB/ Apache Maven Packages</name>
     <url>https://maven.pkg.github.com/Principalribeiroednilson1234/Site_Gostar/DB/</url>
   </repository>
</distributionManagement>

mvn deploy

[INSTALANDO PACOTE]
<dependencies>
 <dependency>
    <groupId>com.example_Site_Gostar</groupId>
    <artifactId>test_Like_DB.Sql</artifactId>
    <version>1.0.0-SNAPSHOT_modelo.css</version>
  </dependency>
</dependencies>

mvn install
git init
git ad .
git commint -m "Commit initial: Project0 Jakarta EE"
git branch -M main
git remote add origin https://github.com